#! /bin/bash

echo "Fetching the date of each debug..."
for I in *-riak-debug; do NODE=${I//-riak-debug/}; echo "`echo $I | awk -F/ '{print $(NF-1)}'`: `cat $I/commands/date`"; done;
printf "\n"

echo "Creating Combined console.log."
for I in *-riak-debug; do NODE=${I//-riak-debug/}; for J in {$I/logs/platform_log_dir/console.log,$I/logs/platform_log_dir/console.log.?}; do sed -n -e '/^201/!{H;d;};/^201/{x;s/\n/ /g;p;};${x;s/\n/ /g;p;}' $J | awk '!/^$/{print $1"T"$2,"'${NODE}'",$0}' | sed 's/\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^ ]*\) \(.*\)/\1 \2 \5/' >> temp.log ; done; done; sort temp.log > combined_console.log;rm temp.log;
printf "\n"

echo "Creating Combined error.log."
for I in *-riak-debug; do NODE=${I//-riak-debug/}; for J in {$I/logs/platform_log_dir/error.log,$I/logs/platform_log_dir/error.log.?}; do sed -n -e '/^201/!{H;d;};/^201/{x;s/\n/ /g;p;};${x;s/\n/ /g;p;}' $J | awk '!/^$/{print $1"T"$2,"'${NODE}'",$0}' | sed 's/\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^ ]*\) \(.*\)/\1 \2 \5/' >> temp.log ; done; done; sort temp.log > combined_error.log;rm temp.log;
printf "\n"

echo "Checking for LevelDB Compaction Errors."
find . -name "LOG" -exec grep -l 'Compaction error' {} \;
printf "\n"

echo "Checking for LevelDB Stalls."
find . -name "LOG" -exec grep -l 'waiting' {} \; | wc -l
printf "\n"

echo "Fetching Non-Zero Swappiness Information."
grep -s -H 'swappiness' */commands/sysctl_linux | grep -v "vm.swappiness = 0" | awk '{print    $0}'
grep -s -H 'swappiness' */commands/sysctl | grep -v "vm.swappiness = 0" | awk '{print    $0}'
printf "\n"

echo "Looking for Non-Zero Overcommit Strategies."
grep -s -H 'overcommit_memory' */commands/sysctl_linux | grep -v "vm.overcommit_memory = 0" | awk '{print    $0}'
grep -s -H 'overcommit_memory' */commands/sysctl | grep -v "vm.overcommit_memory = 0" | awk '{print    $0}'
printf "\n"

echo "Looking for OOM killer Activity"
grep -s -H 'oom-killer' */commands/dmesg | grep "invoked oom-killer" | awk '{print    $0}'
grep -s -H 'oom-killer' */commands/messages | grep "invoked oom-killer" | awk '{print    $0}'
printf "\n"

echo "Looking for Nodes and Drives set to CFQ."
grep -B1 '\[cfq\]' */commands/schedulers | grep -v '\[cfq\]' | grep -v "\-\-" | awk -F"-" '{print "    ",$1,"   ",$4}' | sort
printf "\n"

echo "Counting Large Objects in Logfiles."
grep -i "Large Object" combined_console.log > large_object.log
wc -l large_object.log
printf "\n"

echo "Checking for potential AAE Hashtree Corruption"
grep -i "Corruption" combined_console.log | grep -v CRASH | awk '{print $2" "$5}' | sort -u | sed s/://g  > corruption.log
wc -l corruption.log
printf "\n"

echo "Counting sibling messages in Logfiles."
grep -i "Too many siblings" combined_console.log > siblings.log
wc -l siblings.log
printf "\n"

echo "Checking for file handle exhaustion."
grep "emfiles" combined_error.log | wc -l
printf "\n"

echo "Checking for Erlang resource exhaustion."
grep "system_limit" combined_error.log | wc -l
printf "\n"

echo "Removing Spammy Log Events."
grep -v "Too many siblings" combined_console.log | 
    grep -v "Unrecognized message" |
    grep -v "perhaps_log_throttle_change" |
    grep -v "Heartbeat is misconfigured" |
    grep -v "monitor long_schedule" |
    grep -v "{shutdown,max_concurrency}"|
    grep -v "There's no NAT mapping"  > combined_console.log.nospam
printf "\n"
	
	
#Transparent Hugepages
echo "Checking for Transparent Hugepages (values above 0)."
grep -s -H 'AnonHugePages' */commands/meminfo | awk -F":| *" '$4 > 0 {print  $1 ": "  $4 " " $5}'
printf "\n"

#IO tuning
echo "Checking for dirty_ratio and dirty_background_ratio."
grep -s -H -e 'dirty.*ratio' */commands/sysctl | awk '$3 > 0 {print $1 ": " $3}'
printf "\n"


#TCP connections in netstat
echo "Checking for suspended TCP connections."
echo "Found `grep -s 'TIME_WAIT' */commands/netstat_an | wc -l` connections in TIME_WAIT state."
printf "\n"
